### ISSUE TITLE
Search on module description and title

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/Modularity#14]
This was mentioned by the editors on Höör: It would be nice if it was possible to search on the module description. Seems to me like a very good idea.

When testing this I found that the search seemed very inconsist. I'm not sure what it matches on actually. I would have guessed titles but that doesn't seem to be the case.

<img width="985" alt="_lokal_miljo__posts_ _hoors_kommun_ _wordpress" src="https://cloud.githubusercontent.com/assets/34488/22025981/b1f3bf38-dccf-11e6-9173-aa89ff70cc3a.png">

**Comment by perifer** [comment]
I found the reason for the broken search: https://github.com/helsingborg-stad/Modularity/blob/master/source/php/Search.php#L96

I can't understand what moduleSearch() tries to do actually so I can't debug this. But completely disabling this at least brings back consistent results. With this enabled the page count is for example wrong, and the result is mixed with other post types.

**Comment by Svanmark** [comment]
ModuleSearch is supposed to search modularity modules. I think this may be broken since Modularity 2.0.

**Comment by perifer** [comment]
Not sure, I reported inconsistent search on Jan 17. Inconsistent could still mean that I still doesn't understand exactly what is going on though.

**Comment by perifer** [comment]
#20 is merged, but this is not resolved.  Can you reproduce the oddities I'm seeing or is it just I who misinterpreters the functionality?

**Comment by sebastianthulin** [comment]
I have reproduced the "mixed post types" issue. Looking into a more straight forward solution here.
