### ISSUE TITLE
Sort on meta field

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/Modularity#15]
I continue to have issues when trying to sort on a meta field in the posts module. This is what I have found so far:

Sorting on fields except meta fields seems to work.
Sorting on any meta fields seems to use post_date.

This is what I get with wp debug bar with `define('SAVEQUERIES', true);` set when sorting on a meta filed called event_place:

```
SELECT posts.* FROM posts LEFT JOIN postmeta ON ( posts.ID = postmeta.post_id ) LEFT JOIN postmeta AS mt1 ON (posts.ID = mt1.post_id AND mt1.meta_key = 'event_place' ) WHERE 1=1 AND ( 
postmeta.meta_key = 'event_place' 
OR 
mt1.post_id IS NULL
) AND posts.post_type = 'evenemang' AND ((posts.post_status = 'publish')) GROUP BY posts.ID ORDER BY posts.post_date DESC
```

Notice that it seems to know about event_place but still sorts on post_date. This is what `var_dump($getPostsArgs);` gives in `Posts.php`:

```
array (size=5)
  'posts_per_page' => string '-1' (length=2)
  'post_type' => string 'evenemang' (length=9)
  'order' => string 'desc' (length=4)
  'orderby' => string '_metakey_event_place' (length=20)
  'meta_query' => 
    array (size=3)
      'relation' => string 'OR' (length=2)
      0 => 
        array (size=2)
          'key' => string 'event_place' (length=11)
          'compare' => string 'EXISTS' (length=6)
      1 => 
        array (size=2)
          'key' => string 'event_place' (length=11)
          'compare' => string 'NOT EXISTS' (length=10)
```

It might not be related but I think it might be something similair on the archive page which also have a settings to sort on meta fields.

**Comment by perifer** [comment]
I created two pull request for this issue:

https://github.com/helsingborg-stad/Municipio/pull/18
https://github.com/helsingborg-stad/Modularity/pull/16

**Comment by perifer** [comment]
https://github.com/helsingborg-stad/Municipio/pull/18 is merged. I think the meta_query might be behave differently with posts that don't have the meta field, compared to using the simpler

```
$query->set('orderby', 'meta_value');	
$query->set('meta_key', 'start_date');
```

I think the simpler approach might exclude posts that don't have the meta field. Needs testing though. And not sure if it's a problem with this use-case.

**Comment by perifer** [comment]
Is there any reason this hasn't been merged? This should be the same approach as in https://github.com/helsingborg-stad/Municipio/pull/18 (which is merged).

**Comment by sebastianthulin** [comment]
This has not been merged yet due to lack of documentation about the solution. What are the effects of the change and why does i work?

**Comment by perifer** [comment]
Also see https://github.com/helsingborg-stad/Modularity/pull/16#issue-203582489

**Comment by perifer** [comment]
FYI I've currently postsponed work on this since I don't think we will need this fix when we are using your new event solution.
