### ISSUE TITLE
Q: Bound to ACF and specific blade?

### ISSUE THREAD

**Issue by ekandreas** [helsingborg-stad/Modularity#21]
Hi!
Is this plugin bound to ACF and the old blade engine?
Do you think it is possible to run this with Bladerunner and no ACF?

**Comment by sebastianthulin** [comment]
This plugins base modules is tightly integrated with ACF. However, with some polyfill functions for acf function get_field, you might get the base logic to work without ACF. 

We have not tested to run blade runner. This may be harder to integrate good. I am not aware of the differences between "old" and "new" blade engine, but if the differences are small there might be a chance to just require a newer version of blade in composer.

**Comment by ekandreas** [comment]
No problems using neither blade engines :-)

**Comment by sebastianthulin** [comment]
Cool. What are the benefits of using bladerunner as engine instead of existing solution?

**Comment by ekandreas** [comment]
Bladerunner uses the same underlying Laravel components.
Benefits like active plugin development and controllers are great :-)
Bladerunner has the same code base / approach as Roots/Sage.

**Comment by ekandreas** [comment]
But PhiloNL has a really simple and clean approach. That is great as well.

**Comment by sebastianthulin** [comment]
Okay, grate! I will think about it for the future.

**Comment by ekandreas** [comment]
I can report that the approach of mixing engines fall out very well. Modularity is going to be a standard component in future WordPress development and customer delivery.
