### ISSUE TITLE
No ACF sync

### ISSUE THREAD

**Issue by ekandreas** [helsingborg-stad/Modularity#24]
I need a way to prevent autosync for ACF field groups built in. We don't use the plugins predefined modules with fields and need a way to prevent these from ACF sync.
I could manually mute the fieldgroups but it would be nice to prevent these from being exposed if not selected / enabled modules.

**Comment by ekandreas** [comment]
Perhaps not an issue, I'm going to solve this in my ACF sync script via `get_option('modularity-options')` but it would be nice if wp doesn't get cluttered with settings not used.

**Comment by sebastianthulin** [comment]
This may have something to do with https://github.com/helsingborg-stad/acf-export-manager rather than Modularity. A filter may be suitable in this class, or wrap the array sent to Export functionality.
