### ISSUE TITLE
Import module makes duplicate module

### ISSUE THREAD

**Issue by ekandreas** [helsingborg-stad/Modularity#31]
When using "Import" in the module container we get a duplicate module added and not as expected imported data. Please confirm that this is the intended functionality if so.
We would like a "import" function that copies the fields data instead of creating a duplicate of the same module.

**Comment by ekandreas** [comment]
To reproduce:
Create a module on a page. Put some data in it and save.
Then create a new module and import from the first one.
Change som data in the second module and save.
Now, check the first module data and it's data is modified from the second edit/change.

We would like the second module with imported data to have it's own isolated data.

**Comment by sebastianthulin** [comment]
This behavoir is intended. A new function may be good mainly for smaller sites that provides a "duplicate" functionality. There are at the moment no plan to implement such feature. An graphical indication of intended behaviour may be needed to make the UI more clear.

**Comment by ekandreas** [comment]
Then please change the name and icon for the function. Import is where you import data, not creating a new reference 😂

**Comment by sebastianthulin** [comment]
Do you have any suggestions for a better naming of the function? The import "naming" is due to that you are importing the id to the list (a new entry to the list that is independent from the actual module).

**Comment by ekandreas** [comment]
We just can’t understand the meaning of the function. When is it going to be used?
I would turn the ux the other eay around. 
Instead of creating a new module and override it with ”import” it would be much more understandable with a direct button called ”duplicate” without the need of creating a fake and useless module before ”import”.

**Comment by ekandreas** [comment]
How to do if you want to copy a module?

**Comment by ekandreas** [comment]
We are planning to hide the button to the user because we just can’t see the meaning of an ”import” doing reference duplication.

**Comment by sebastianthulin** [comment]
There are not any feature for duplicating a module and it's content. The existing feature that you are referring to is the most used function (except for creating new modules) in modularity in our organisation. 

One example when we use it are when we need to display contact information on multiple pages. One update to a single module is more efficient than updating the same information multiple times. 

You may however submit a pull-request for duplication functionality.

**Comment by ekandreas** [comment]
But why create a useless module before ”import”? Don’t understand the process. It just clutters the database and makes the process harder.

**Comment by sebastianthulin** [comment]
I see. If you don't click "edit" before you import a module the useless post won't be created (if it is created it's a serious bug). A new post should only be created by draging a module from the sidebar and clicking "edit" button.

**Comment by ekandreas** [comment]
Ok. Closing this issue. 
Perhaps ”convert” would be a better name?
