### ISSUE TITLE
Can't enqueue scripts when using a module as a plugin

### ISSUE THREAD

**Issue by davidohlin** [helsingborg-stad/Modularity#34]
Hi!

I'm creating a plugin for Modularity and want to enqueue a script. I'm using the `script()` method like this:

```
public function script()
{
    wp_register_script('mod-accordion-js', plugins_url( '/assets/js/mod-accordion.js', __FILE__ ), array(), '', true);
    wp_enqueue_script('mod-accordion-js');
}
```

I can only get this working by re-invoking `wp_enqueue_scripts()` on line 140 of `modularity/source/php/Module.php`, which I assume is a horrible idea:

```
...
        if (!is_admin() && $this->hasModule()) {
            add_action('wp_enqueue_scripts', array($this, 'style'));
            add_action('wp_enqueue_scripts', array($this, 'script'));
            do_action('wp_enqueue_scripts');
        }
...
```

Am I missing something?

Thanks!

**Comment by sebastianthulin** [comment]
I'm shure thats a horrible idea. ;). I can recall that we have had some issues before with this in some enviroments. The styles are registrered on the module __construct. This may be too early or too late, depending on when you invoke "modularity_register_module" in your plugin. You should hook your registration of the module on the hook "Modularity" (not plugins_loaded). 

Do you have some code that produces this error?

**Comment by davidohlin** [comment]
😄 Yes, here's the plugin repo: [https://github.com/RegionHalland/mod-accordion](https://github.com/RegionHalland/mod-accordion)

Thanks for the quick reply!

**Comment by sebastianthulin** [comment]
Seems to be a core issue. The module construct is called to late. The module call happends in content-context where styles already has been printed to the page. I will have a go on restructuring the calls to provide the functionality.

**Comment by sebastianthulin** [comment]
In contradiction to above; I can actually get this working. The styles & css is enqueued correctly on the page that the module appears on (in other words not all pages). What version are you running of Modularity?

**Comment by davidohlin** [comment]
I'm using version 1.6.5. I've applied the changes from [this pull request](#33), but even with a fresh install of Modularity I can't get it to work. What theme were you using when you got this working..? We're using is a modified version of (Sage)[https://roots.io/sage/]. I

**Comment by sebastianthulin** [comment]
Latest release is 2.3.51, do you have the ability to update? We are using latest version of Municipio.

**Comment by davidohlin** [comment]
Updated to 2.3.51, having the same issue. I will look further into this and try to get back with more ideas on what might cause it. Meanwhile, the theme we're using can be found [here](https://github.com/RegionHalland/halland). 

Thanks!
